[tool.poetry]
name = "repl_python3_Testrepro"
version = "0.1.0"
description = ""
authors = ["NoQuarter1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
logger = "^1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
